# Generated by Django 3.2.6 on 2021-11-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='suject',
            new_name='subject',
        ),
    ]
